spring.application.name=dbilleteras-virtuales


spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o
spring.data.mongodb.uri=mongodb://localhost:27017/fintech_db
spring.data.mongodb.database=fintech_db

jwt.secret=dGVzdFNlY3JldEtleVBhcmFKV1RGaW50ZWNoQmlsbGV0ZXJhc2IwMjY=
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=walletteachdata@gmail.com
spring.mail.password=edgl oagm qsmk mvrs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true