spring.application.name=dbilleteras-virtuales

spring.data.mongodb.uri=mongodb://localhost:27017/fintech_db
spring.data.mongodb.database=fintech_db

jwt.secret=dGVzdFNlY3JldEtleVBhcmFKV1RGaW50ZWNoQmlsbGV0ZXJhczIwMjY=
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG